### GET ALL FRIENDS BELONGING TO A USER
GET https://localhost:3001/friends HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbSIsImlkIjoxLCJpYXQiOjE3NDQ2NTQzMzQsImV4cCI6MTc0NDY1NzkzNH0.DI556OdOPvXbAgPSPpqftaZeSZ8wga7ADkheurt2gqU

### SEND FRIEND REQUEST
POST https://localhost:3001/friend-requests/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbSIsImlkIjoxLCJpYXQiOjE3NDQ2NTQzMzQsImV4cCI6MTc0NDY1NzkzNH0.DI556OdOPvXbAgPSPpqftaZeSZ8wga7ADkheurt2gqU

### DELETE FRIEND
DELETE https://localhost:3001/friends/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbSIsImlkIjoxLCJpYXQiOjE3NDQ2NTQzMzQsImV4cCI6MTc0NDY1NzkzNH0.DI556OdOPvXbAgPSPpqftaZeSZ8wga7ADkheurt2gqU

### ACCEPT FRIEND REQUEST
PATCH https://localhost:3001/friend-requests/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbSIsImlkIjoxLCJpYXQiOjE3NDQ2NTQzMzQsImV4cCI6MTc0NDY1NzkzNH0.DI556OdOPvXbAgPSPpqftaZeSZ8wga7ADkheurt2gqU

### GET FRIENDS ONLINE STATUS
GET https://localhost:3001/friends/2/status HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpbSIsImlkIjoxLCJpYXQiOjE3NDQ2NTQzMzQsImV4cCI6MTc0NDY1NzkzNH0.DI556OdOPvXbAgPSPpqftaZeSZ8wga7ADkheurt2gqU