export { default as LandingPage } from './LandingPage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as DesignSystemDemo } from './DesignSystemDemo'
export { default as GamePage } from './GamePage'