export { default as PlayerManagement } from './PlayerManagement'
export { default as GameStats } from './GameStats'
export { default as MatchHistory } from './MatchHistory'
export { default as QuickPlay } from './QuickPlay'
export { default as TopPlayers } from './TopPlayers' 